name 'server_setup'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures server_setup'
long_description 'Installs/Configures server_setup'
version '0.1.0'

depends 'server_setup'
provides 'server_setup::default'
supports 'ubuntu'
